### ISSUE TITLE
Please remove/disable recursive by default

### ISSUE THREAD

**Issue by alecthomas** [nishanths/predeclared#1]
This feature is useful sometimes, but is generally not what you want as a user, particularly as it recurses even through vendor directories.

**Comment by nishanths** [comment]
Thanks. This was done to keep to be consistent with commands such as `gofmt` and `go tool vet`, which recurse directories (including vendor directories) by default. Would a flag like this help?

```
-r   recurse directories (default true)
```

And used like:

```
predeclared -r=false path/to/dir
```

**Comment by nishanths** [comment]
This command now uses the go/analysis package https://godoc.org/golang.org/x/tools/go/analysis, which defines a standard way to specify and interpret filepath/package arguments for Go linters. Closing.
